version: '3.8'

services:
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile # If the Dockerfile is named Dockerfile (default)
    ports:
      - "8080:8080" # Mapping local port 8080 to container port 8080
    environment:
      - WEATHER_API_KEY
    depends_on:
      - redis # This ensures the Redis container starts first

  redis:
    image: "redis:latest" # Use the latest Redis image
    ports:
      - "6379:6379" # Mapping local port 6379 to container port 6379
    volumes:
      - redis-data:/data # Persistent data storage for Redis

volumes:
  redis-data: # Define a volume for Redis data persistence